"""Isolated read-only staff guidance with no DB, network or action access."""
from __future__ import annotations
import re

VERSION="2026.08.2"
MAX_QUESTION_LENGTH=1200
ARTICLES=(
 {"id":"workflow","keys":"änderung antrag prüfen genehmigen freigabe workflow review approve طلب تعديل مراجعة اعتماد","de":"Amtliche Daten werden nie direkt geändert. Der Ablauf lautet: Antrag, automatische Prüfung, unabhängige fachliche Prüfung, Genehmigung, Publikation und Historisierung. Antragsteller und Genehmiger müssen getrennt sein.","en":"Official data is never edited directly. Use request, automatic validation, independent review, approval, publication and history. Requester and approver must be different people.","ar":"لا تُعدّل البيانات الرسمية مباشرة. المسار هو طلب، تحقق آلي، مراجعة فنية مستقلة، اعتماد، نشر وحفظ النسخة السابقة. يجب فصل مقدم الطلب عن المعتمد.","sources":["docs/ROLES_AND_MUNICIPAL_WORKFLOW.md","docs/NATIONAL_SYSTEM_BLUEPRINT.md"]},
 {"id":"addressing","keys":"adresse hausnummer straße eingang postleitzahl address street entrance postal عنوان رقم منزل شارع مدخل بريدي","de":"Gebäude, Eingang und Adresse sind getrennte Objekte. Eine Hausnummer wird dem geprüften Eingang mit Straße, sechsstelliger Postleitzahl, Koordinate, Quelle und Qualitätsstufe zugeordnet. Erst die Genehmigung macht sie amtlich.","en":"Building, entrance and address are separate objects. A house number is linked to a verified entrance with street, six-digit postal code, coordinates, source and quality level. It becomes official only after approval.","ar":"المبنى والمدخل والعنوان كائنات منفصلة. يُربط رقم المنزل بالمدخل المتحقق منه مع الشارع والرمز البريدي والإحداثيات والمصدر ودرجة الجودة، ولا يصبح رسمياً إلا بعد الاعتماد.","sources":["docs/POSTAL_CODE_CONCEPT.md","docs/OBJECT_CATALOG_V0.1.md"]},
 {"id":"cadastre","keys":"kataster flur flurstück grundstück gebäude eigentümer cadastral parcel building owner عقار قطعة مقسم مبنى مالك","de":"Die Erfassungsfolge ist Katasterbezirk, Flur, Flurstück, Gebäude, Eingang und Adresse. Eigentümer- und Rechtsangaben gehören ausschließlich in das besonders geschützte Rechtsregister und niemals in öffentliche Karten oder Exporte.","en":"Capture cadastral district, section, parcel, building, entrance and address in that order. Ownership and legal records belong only in the protected legal register and never in public maps or exports.","ar":"ترتيب التسجيل هو المنطقة العقارية ثم القسم ثم القطعة ثم المبنى ثم المدخل والعنوان. بيانات الملكية والحقوق تحفظ فقط في السجل القانوني المحمي ولا تظهر في الخرائط أو الصادرات العامة.","sources":["docs/DATA_MODEL.md","docs/SECURITY.md"]},
 {"id":"roles","keys":"rolle rechte zugriff editor prüfer auditor administrator role permission access صلاحية دور مدقق مدير","de":"Es gilt das Minimalprinzip. Kommunale Bearbeitung erfasst, Vermessung prüft Geometrien, Reviewer prüfen fachlich, Approver genehmigen, Auditoren lesen Protokolle und Administratoren betreiben Technik. Niemand darf allein erfassen und endgültig genehmigen.","en":"Least privilege applies. Editors capture, surveyors validate geometry, reviewers review, approvers authorize, auditors read logs and administrators operate technology. Nobody may submit and finally approve alone.","ar":"يطبق مبدأ أقل صلاحية. يسجل الموظف، ويتحقق المساح، ويراجع المدقق، ويعتمد المخول، ويقرأ المراجع السجلات، ويدير المسؤول التقنية. لا يجوز لشخص واحد التسجيل والاعتماد النهائي.","sources":["docs/ROLES_AND_MUNICIPAL_WORKFLOW.md","docs/SECURITY.md"]},
 {"id":"security","keys":"sicherheit passwort mfa phishing export usb backup ransomware security password أمن كلمة مرور نسخ احتياطي تصيد","de":"Nutzen Sie nur Ihr persönliches Konto und MFA, öffnen Sie keine unbekannten Anhänge und exportieren Sie nur dienstlich erforderliche Daten. Verdächtige Vorgänge sofort dem Sicherheitsbetrieb melden. Backups werden getrennt und unveränderbar aufbewahrt.","en":"Use only your personal account and MFA, do not open unknown attachments and export only data required for official duties. Report suspicious activity immediately. Backups are separate and immutable.","ar":"استخدم حسابك الشخصي والمصادقة المتعددة فقط، ولا تفتح المرفقات المجهولة، ولا تصدر إلا البيانات اللازمة للعمل. أبلغ الأمن فوراً عن أي نشاط مشبوه وتحفظ النسخ الاحتياطية منفصلة وغير قابلة للتعديل.","sources":["docs/SECURITY.md","docs/AIR_GAPPED_OPERATION.md"]},
 {"id":"offline","keys":"offline internet synchronisation server netz disconnected مزامنة دون اتصال انترنت خادم","de":"Öffentliche Grunddaten können lokal verfügbar bleiben. Amtliche Schreibvorgänge benötigen immer den lokalen Behördenserver, damit Rollen, Konfliktprüfung und Auditkette erhalten bleiben. Geschützte Daten liegen nicht im Browsercache.","en":"Public base data can remain local. Official writes always require the local authority server so roles, conflict checks and audit history remain effective. Protected data is not browser-cached.","ar":"يمكن أن تبقى البيانات العامة متاحة محلياً. تتطلب الكتابة الرسمية خادم الجهة المحلي للحفاظ على الأدوار وفحص التعارض وسلسلة التدقيق. لا تحفظ البيانات المحمية في ذاكرة المتصفح.","sources":["docs/AIR_GAPPED_OPERATION.md"]},
 {"id":"quality","keys":"qualität quelle status draft official genauigkeit quality source accuracy جودة مصدر دقة رسمي مسودة","de":"Jedes Objekt benötigt Quelle, Qualitätsstufe und Freigabestatus. DRAFT und OPEN_DATA_UNVERIFIED sind nicht rechtsverbindlich. Nur geprüfte, genehmigte und als OFFICIAL veröffentlichte Datensätze sind amtlich.","en":"Every object needs a source, quality level and approval status. DRAFT and OPEN_DATA_UNVERIFIED are not authoritative. Only verified, approved and published OFFICIAL records are official.","ar":"يحتاج كل كائن إلى مصدر ودرجة جودة وحالة اعتماد. المسودة والبيانات المفتوحة غير المتحققة ليست رسمية. فقط السجلات المتحققة والمعتمدة والمنشورة بحالة رسمية تعد معتمدة.","sources":["docs/VALIDATION.md","docs/OBJECT_CATALOG_V0.1.md"]}
)
ARTICLES+=(
 {"id":"overview","keys":"system funktion übersicht start portal navigation was kann system feature overview نظام وظائف نظرة عامة ماذا يفعل","de":"Das System verwaltet öffentliche Adressen, interne Katasterobjekte und besonders geschützte Rechtsdaten in getrennten Bereichen. Mitarbeiter arbeiten mit Bestandsdaten, Suche, Aufgaben, Karten, Objektakten, geregelten Änderungen, Außendienst und Audit. Der aktuelle Stand ist ein Produktionskandidat und noch kein staatlich freigegebenes Register.","en":"The system manages public addresses, internal cadastre objects and specially protected legal data in separate domains. Staff use register data, search, tasks, maps, dossiers, controlled changes, field work and audit. The current release is a production candidate, not yet an authorized state register.","ar":"يدير النظام العناوين العامة وبيانات السجل العقاري الداخلية والبيانات القانونية شديدة الحماية في نطاقات منفصلة. يستخدم الموظفون بيانات السجل والبحث والمهام والخرائط والملفات والتعديلات المنظمة والعمل الميداني والتدقيق. الإصدار الحالي مرشح للإنتاج وليس سجلاً حكومياً معتمداً بعد.","sources":["README.md","docs/NATIONAL_SYSTEM_BLUEPRINT.md"]},
 {"id":"login_profile","keys":"anmelden login profil abmelden sitzung konto benutzer password session sign in profile تسجيل دخول ملف مستخدم جلسة حساب","de":"Melden Sie sich nur mit Ihrem persönlichen Behördenkonto an. Im Profil finden Sie Aufgaben, Schnellsuche, Mitarbeiter-Assistent, Hilfe und Abmelden; Systemeinstellungen erscheinen nur für Systemadministratoren. Sitzungen sind zeitlich begrenzt. Bei unbekannten Anmeldungen oder Kontoproblemen sofort Support und Sicherheitsbetrieb informieren.","en":"Sign in only with your personal authority account. The profile contains tasks, quick search, staff assistant, help and sign-out; system settings appear only to system administrators. Sessions expire. Report unknown sign-ins or account problems immediately.","ar":"سجّل الدخول فقط بحسابك الحكومي الشخصي. يحتوي الملف على المهام والبحث السريع ومساعد الموظفين والمساعدة وتسجيل الخروج، وتظهر إعدادات النظام لمدير النظام فقط. الجلسات محدودة زمنياً ويجب الإبلاغ فوراً عن أي دخول غير معروف.","sources":["README.md","docs/SECURITY.md"]},
 {"id":"search_map","keys":"suche finden karte layer satellit 3d koordinaten search map filter layers بحث خريطة طبقات قمر إحداثيات","de":"Die Suche findet Adressen, Straßen, Gebäude, Orte, Objekt- und Aktennummern. Auf der Karte können lokale Straßen, Gebäude, amtliche Adressen, Hausnummern und Katasterdarstellung ein- oder ausgeblendet werden. Satelliten- und externe Basiskarten benötigen Internet oder einen staatlichen internen Tile-Server; Fachgeometrien bleiben lokal.","en":"Search covers addresses, roads, buildings, places, object IDs and file references. The map can show local roads, buildings, official addresses, house numbers and the cadastral view. Satellite and external basemaps require internet or an internal state tile server; domain geometry remains local.","ar":"يشمل البحث العناوين والطرق والمباني والأماكن ومعرفات الكائنات وأرقام الملفات. تعرض الخريطة الطرق والمباني والعناوين الرسمية وأرقام المنازل وطبقة السجل العقاري. تحتاج صور الأقمار وخرائط الأساس الخارجية إلى الإنترنت أو خادم بلاطات حكومي داخلي، بينما تبقى الهندسة الفنية محلية.","sources":["README.md","docs/AIR_GAPPED_OPERATION.md"]},
 {"id":"parcel_capture","keys":"flur anlegen flurstück erfassen polygon zeichnen parcel capture section geometry create قطعة عقار قسم رسم مضلع تسجيل","de":"Zuerst wird eine Katasterflur mit eindeutiger Nummer angelegt. Danach wird das Flurstück als geschlossene, gültige Polygongeometrie innerhalb des zuständigen Verwaltungsgebiets erfasst. Quelle, Qualitätsstufe und Status sind Pflicht. Die Fläche wird aus der Geometrie berechnet und bleibt bis zur Vermessungsfreigabe vorläufig.","en":"Create a uniquely numbered cadastral section first, then capture the parcel as a closed valid polygon within the assigned administrative area. Source, quality and status are mandatory. Area is geometry-derived and provisional until survey approval.","ar":"يُنشأ أولاً قسم عقاري برقم فريد، ثم تُسجل القطعة كمضلع مغلق وصحيح داخل النطاق الإداري المختص. المصدر ودرجة الجودة والحالة إلزامية، وتحسب المساحة من الهندسة وتبقى مؤقتة حتى اعتماد المساحة.","sources":["docs/DATA_MODEL.md","docs/OBJECT_CATALOG_V0.1.md"]},
 {"id":"building_fieldwork","keys":"gebäude erfassen vermessung außendienst foto gps schild briefkasten montage building survey field photo plaque mailbox مبنى مسح ميدان صورة موقع لوحة صندوق بريد","de":"Ein Gebäude wird mit Geometrie, Objektkennung, Quelle und Qualität erfasst und einem Flurstück zugeordnet. Der Außendienst dokumentiert den genauen Eingang, GPS-Genauigkeit, Gerätezeit, Foto sowie montiertes Hausnummernschild und Briefkasten. Danach folgen unabhängige Prüfung und Genehmigung.","en":"A building is captured with geometry, object ID, source and quality and linked to a parcel. Field staff record the exact entrance, GPS accuracy, device time, photo, house-number plaque and mailbox installation. Independent review and approval follow.","ar":"يُسجل المبنى مع هندسته ومعرفه ومصدره وجودته ويربط بقطعة عقارية. يوثق العمل الميداني المدخل الدقيق ودقة GPS ووقت الجهاز والصورة وتركيب لوحة الرقم وصندوق البريد، ثم تتم المراجعة والاعتماد بشكل مستقل.","sources":["docs/ROLES_AND_MUNICIPAL_WORKFLOW.md","docs/DATA_MODEL.md"]},
 {"id":"tasks_notifications","keys":"aufgaben benachrichtigung offen warten submitted reviewed task notification pending مهام إشعارات انتظار مراجعة اعتماد","de":"Unter „Meine Aufgaben“ sehen Beschäftigte offene Vorgänge ihres Arbeitsbereichs. SUBMITTED wartet auf fachliche Prüfung, REVIEWED auf Genehmigung, APPROVED ist freigegeben; CANCELLED und REJECTED bleiben in der Historie. Benachrichtigungen zeigen wartende Prüfungen, Freigaben und Änderungen, ersetzen aber keine fachliche Kontrolle.","en":"My tasks shows open cases for the employee's scope. SUBMITTED awaits professional review, REVIEWED awaits approval, APPROVED is authorized; CANCELLED and REJECTED remain in history. Notifications show pending reviews, approvals and changes but do not replace professional checks.","ar":"تعرض «مهامي» المعاملات المفتوحة ضمن نطاق الموظف. حالة SUBMITTED تنتظر المراجعة، وREVIEWED تنتظر الاعتماد، وAPPROVED معتمدة، بينما تبقى المعاملات الملغاة والمرفوضة في السجل. الإشعارات لا تستبدل التحقق الفني.","sources":["docs/ROLES_AND_MUNICIPAL_WORKFLOW.md"]},
 {"id":"documents_exports","keys":"pdf objektakte drucken export geojson kml csv google post rettung dossier print document تصدير طباعة ملف pdf خرائط بريد إسعاف","de":"PDF-Objektakten enthalten nur für die jeweilige Rolle zulässige Daten und kennzeichnen Entwurf oder amtlichen Status. Öffentliche GeoJSON-, KML- und CSV-Exporte dürfen ausschließlich freigegebene Adressen ohne Eigentümer- oder Bewohnerdaten enthalten. Übergaben brauchen Empfänger, Rechtsgrundlage, Filter, Prüfsumme, Freigabe und Zeitpunkt.","en":"PDF dossiers contain only role-permitted data and identify draft or official status. Public GeoJSON, KML and CSV exports may contain only approved addresses without owner or resident data. Transfers require recipient, legal basis, filter, checksum, approval and time.","ar":"تحتوي ملفات PDF فقط على البيانات المسموح بها للدور وتوضح حالة المسودة أو الرسمية. لا تتضمن صادرات GeoJSON أو KML أو CSV العامة إلا العناوين المعتمدة دون بيانات المالك أو السكان. يحتاج التسليم إلى مستلم وأساس قانوني وتصفية وبصمة واعتماد ووقت.","sources":["docs/DATA_DISTRIBUTION_AND_COMMERCIAL_USE.md","README.md"]},
 {"id":"backup_recovery","keys":"backup restore wiederherstellung ausfall rpo rto sicherung standort disaster نسخ احتياطي استعادة فشل موقع طوارئ","de":"Es gilt 3-2-1-1-0: mindestens drei Kopien auf zwei Speichersystemen, eine Kopie an einem anderen Standort, eine unveränderbare oder offline Kopie und null ungeprüfte Restore-Fehler. Wiederherstellungen werden isoliert getestet. Standort B übernimmt bei Ausfall; der Pilot zielt auf RPO 15 Minuten und RTO 4 Stunden, vorbehaltlich staatlicher Abnahme.","en":"Use 3-2-1-1-0: at least three copies on two storage systems, one off-site, one immutable or offline and zero untested restore errors. Restores are tested in isolation. Site B takes over on failure; pilot targets are 15-minute RPO and four-hour RTO pending state approval.","ar":"يطبق مبدأ 3-2-1-1-0: ثلاث نسخ على نظامي تخزين، نسخة في موقع آخر، نسخة غير قابلة للتعديل أو غير متصلة، وصفر أخطاء استعادة غير مختبرة. تختبر الاستعادة في بيئة معزولة ويتولى الموقع ب التشغيل عند الفشل.","sources":["docs/ARCHITECTURE.md","docs/AIR_GAPPED_OPERATION.md"]},
 {"id":"settings_support","keys":"einstellung standardsprache kartenebene support ticket hilfe problem settings language support help إعدادات لغة خريطة دعم مساعدة مشكلة","de":"Systemadministratoren öffnen Systemeinstellungen über das Profil und verwalten Standardsprache, Kartenebene, Supportkontakt und öffentliche Funktionen. Andere Rollen können diese Werte nicht verändern. Über „Hilfe und Support“ im Profil wird eine Anfrage mit Kategorie, Betreff und Beschreibung erstellt; Sicherheitsvorfälle zusätzlich sofort an den Sicherheitsbetrieb melden.","en":"System administrators open settings from the profile to manage default language, map layer, support contact and public functions. Other roles cannot change them. Help and support creates a categorized ticket with subject and description; security incidents must also be reported immediately to security operations.","ar":"يفتح مدير النظام الإعدادات من الملف لإدارة اللغة الافتراضية وطبقة الخريطة وجهة الدعم والوظائف العامة، ولا تستطيع الأدوار الأخرى تعديلها. تنشئ «المساعدة والدعم» طلباً بفئة وموضوع ووصف، ويجب إبلاغ الأمن فوراً بالحوادث الأمنية.","sources":["README.md","docs/SECURITY.md"]},
 {"id":"production_status","keys":"produktiv fertig freigabe einsatz staat server postgis oidc hsm production ready status جاهز إنتاج اعتماد دولة خادم","de":"Der Stand ist Version 0.19.0 und ein geprüfter Pilot/Produktionskandidat, aber noch nicht für staatlichen Echtbetrieb autorisiert. Blockierend sind insbesondere der aktive SQLite-Adapter statt PostgreSQL/PostGIS, staatlicher OIDC/MFA, HSM-Signaturen, amtlich bestätigte Daten, zwei Betriebsstandorte, isolierte Backups sowie unabhängige Rechts-, Datenschutz-, Sicherheits-, Failover- und Restore-Abnahmen.","en":"Version 0.19.0 is a tested pilot/production candidate, not yet authorized for live state operation. Blockers include the SQLite adapter instead of PostgreSQL/PostGIS, state OIDC/MFA, HSM signatures, authoritative data, two operating sites, isolated backups and independent legal, privacy, security, failover and restore acceptance.","ar":"الإصدار 0.19.0 نموذج تجريبي ومرشح للإنتاج لكنه غير مخول بعد للتشغيل الحكومي الفعلي. تشمل العوائق استبدال SQLite بـ PostgreSQL/PostGIS وربط هوية حكومية ومصادقة متعددة وتوقيعات HSM وبيانات رسمية وموقعين للتشغيل ونسخاً احتياطية معزولة واعتمادات مستقلة.","sources":["deploy/PRODUCTION-READINESS.md","docs/NATIONAL_SYSTEM_BLUEPRINT.md"]}
)
ACTION=re.compile(r"\b(lösch|delete|genehmig|approve|änder|update|exportier|send|sende|erstell|create|نفذ|احذف|اعتمد|عدّل|صدّر|أنشئ)\w*",re.I)
ADVICE=re.compile(r"\b(wie|how|warum|what|erklär|explain|كيف|لماذا|شرح|ما)\b",re.I)
def _tokens(value):return {x for x in re.findall(r"[\w\u0600-\u06ff]+",value.lower()) if len(x)>2}
def answer(question,language="ar"):
 language=language if language in {"ar","en","de"} else "ar";question=(question or "").strip()[:MAX_QUESTION_LENGTH]
 if not question:raise ValueError("question_required")
 ranked=sorted(((len(_tokens(question)&_tokens(a["keys"])),a) for a in ARTICLES),key=lambda x:x[0],reverse=True)
 selected=[a for score,a in ranked if score][:2] or [next(a for a in ARTICLES if a["id"]=="overview")]
 body="\n\n".join(a[language] for a in selected)
 if ACTION.search(question) and not ADVICE.search(question):
  refusal={"de":"Ich kann keine Daten ändern, freigeben, löschen, exportieren oder Aktionen im System ausführen. Ich kann nur den sicheren Ablauf erklären.","en":"I cannot change, approve, delete or export data, or perform system actions. I can only explain the safe procedure.","ar":"لا أستطيع تعديل البيانات أو اعتمادها أو حذفها أو تصديرها أو تنفيذ أي إجراء في النظام. يمكنني فقط شرح المسار الآمن."}[language]
  body=refusal+"\n\n"+body
 return {"answer":body,"topics":[a["id"] for a in selected],"sources":sorted({s for a in selected for s in a["sources"]}),"knowledge_version":VERSION,"knowledge_topics":len(ARTICLES),"matched":any(score for score,_ in ranked),"isolation":{"read_only":True,"database_access":False,"network_access":False,"system_actions":False},"notice":{"de":"Beratungshilfe – keine amtliche Entscheidung.","en":"Guidance only – not an official decision.","ar":"مساعدة إرشادية وليست قراراً رسمياً."}[language]}
