"""Isolated read-only staff guidance with no DB, network or action access."""
from __future__ import annotations
import re

VERSION="2026.08"
MAX_QUESTION_LENGTH=1200
ARTICLES=(
 {"id":"workflow","keys":"änderung antrag prüfen genehmigen freigabe workflow review approve طلب تعديل مراجعة اعتماد","de":"Amtliche Daten werden nie direkt geändert. Der Ablauf lautet: Antrag, automatische Prüfung, unabhängige fachliche Prüfung, Genehmigung, Publikation und Historisierung. Antragsteller und Genehmiger müssen getrennt sein.","en":"Official data is never edited directly. Use request, automatic validation, independent review, approval, publication and history. Requester and approver must be different people.","ar":"لا تُعدّل البيانات الرسمية مباشرة. المسار هو طلب، تحقق آلي، مراجعة فنية مستقلة، اعتماد، نشر وحفظ النسخة السابقة. يجب فصل مقدم الطلب عن المعتمد.","sources":["docs/ROLES_AND_MUNICIPAL_WORKFLOW.md","docs/NATIONAL_SYSTEM_BLUEPRINT.md"]},
 {"id":"addressing","keys":"adresse hausnummer straße eingang postleitzahl address street entrance postal عنوان رقم منزل شارع مدخل بريدي","de":"Gebäude, Eingang und Adresse sind getrennte Objekte. Eine Hausnummer wird dem geprüften Eingang mit Straße, sechsstelliger Postleitzahl, Koordinate, Quelle und Qualitätsstufe zugeordnet. Erst die Genehmigung macht sie amtlich.","en":"Building, entrance and address are separate objects. A house number is linked to a verified entrance with street, six-digit postal code, coordinates, source and quality level. It becomes official only after approval.","ar":"المبنى والمدخل والعنوان كائنات منفصلة. يُربط رقم المنزل بالمدخل المتحقق منه مع الشارع والرمز البريدي والإحداثيات والمصدر ودرجة الجودة، ولا يصبح رسمياً إلا بعد الاعتماد.","sources":["docs/POSTAL_CODE_CONCEPT.md","docs/OBJECT_CATALOG_V0.1.md"]},
 {"id":"cadastre","keys":"kataster flur flurstück grundstück gebäude eigentümer cadastral parcel building owner عقار قطعة مقسم مبنى مالك","de":"Die Erfassungsfolge ist Katasterbezirk, Flur, Flurstück, Gebäude, Eingang und Adresse. Eigentümer- und Rechtsangaben gehören ausschließlich in das besonders geschützte Rechtsregister und niemals in öffentliche Karten oder Exporte.","en":"Capture cadastral district, section, parcel, building, entrance and address in that order. Ownership and legal records belong only in the protected legal register and never in public maps or exports.","ar":"ترتيب التسجيل هو المنطقة العقارية ثم القسم ثم القطعة ثم المبنى ثم المدخل والعنوان. بيانات الملكية والحقوق تحفظ فقط في السجل القانوني المحمي ولا تظهر في الخرائط أو الصادرات العامة.","sources":["docs/DATA_MODEL.md","docs/SECURITY.md"]},
 {"id":"roles","keys":"rolle rechte zugriff editor prüfer auditor administrator role permission access صلاحية دور مدقق مدير","de":"Es gilt das Minimalprinzip. Kommunale Bearbeitung erfasst, Vermessung prüft Geometrien, Reviewer prüfen fachlich, Approver genehmigen, Auditoren lesen Protokolle und Administratoren betreiben Technik. Niemand darf allein erfassen und endgültig genehmigen.","en":"Least privilege applies. Editors capture, surveyors validate geometry, reviewers review, approvers authorize, auditors read logs and administrators operate technology. Nobody may submit and finally approve alone.","ar":"يطبق مبدأ أقل صلاحية. يسجل الموظف، ويتحقق المساح، ويراجع المدقق، ويعتمد المخول، ويقرأ المراجع السجلات، ويدير المسؤول التقنية. لا يجوز لشخص واحد التسجيل والاعتماد النهائي.","sources":["docs/ROLES_AND_MUNICIPAL_WORKFLOW.md","docs/SECURITY.md"]},
 {"id":"security","keys":"sicherheit passwort mfa phishing export usb backup ransomware security password أمن كلمة مرور نسخ احتياطي تصيد","de":"Nutzen Sie nur Ihr persönliches Konto und MFA, öffnen Sie keine unbekannten Anhänge und exportieren Sie nur dienstlich erforderliche Daten. Verdächtige Vorgänge sofort dem Sicherheitsbetrieb melden. Backups werden getrennt und unveränderbar aufbewahrt.","en":"Use only your personal account and MFA, do not open unknown attachments and export only data required for official duties. Report suspicious activity immediately. Backups are separate and immutable.","ar":"استخدم حسابك الشخصي والمصادقة المتعددة فقط، ولا تفتح المرفقات المجهولة، ولا تصدر إلا البيانات اللازمة للعمل. أبلغ الأمن فوراً عن أي نشاط مشبوه وتحفظ النسخ الاحتياطية منفصلة وغير قابلة للتعديل.","sources":["docs/SECURITY.md","docs/AIR_GAPPED_OPERATION.md"]},
 {"id":"offline","keys":"offline internet synchronisation server netz disconnected مزامنة دون اتصال انترنت خادم","de":"Öffentliche Grunddaten können lokal verfügbar bleiben. Amtliche Schreibvorgänge benötigen immer den lokalen Behördenserver, damit Rollen, Konfliktprüfung und Auditkette erhalten bleiben. Geschützte Daten liegen nicht im Browsercache.","en":"Public base data can remain local. Official writes always require the local authority server so roles, conflict checks and audit history remain effective. Protected data is not browser-cached.","ar":"يمكن أن تبقى البيانات العامة متاحة محلياً. تتطلب الكتابة الرسمية خادم الجهة المحلي للحفاظ على الأدوار وفحص التعارض وسلسلة التدقيق. لا تحفظ البيانات المحمية في ذاكرة المتصفح.","sources":["docs/AIR_GAPPED_OPERATION.md"]},
 {"id":"quality","keys":"qualität quelle status draft official genauigkeit quality source accuracy جودة مصدر دقة رسمي مسودة","de":"Jedes Objekt benötigt Quelle, Qualitätsstufe und Freigabestatus. DRAFT und OPEN_DATA_UNVERIFIED sind nicht rechtsverbindlich. Nur geprüfte, genehmigte und als OFFICIAL veröffentlichte Datensätze sind amtlich.","en":"Every object needs a source, quality level and approval status. DRAFT and OPEN_DATA_UNVERIFIED are not authoritative. Only verified, approved and published OFFICIAL records are official.","ar":"يحتاج كل كائن إلى مصدر ودرجة جودة وحالة اعتماد. المسودة والبيانات المفتوحة غير المتحققة ليست رسمية. فقط السجلات المتحققة والمعتمدة والمنشورة بحالة رسمية تعد معتمدة.","sources":["docs/VALIDATION.md","docs/OBJECT_CATALOG_V0.1.md"]}
)
ACTION=re.compile(r"\b(lösch|delete|genehmig|approve|änder|update|exportier|send|sende|erstell|create|نفذ|احذف|اعتمد|عدّل|صدّر|أنشئ)\w*",re.I)
def _tokens(value):return {x for x in re.findall(r"[\w\u0600-\u06ff]+",value.lower()) if len(x)>2}
def answer(question,language="ar"):
 language=language if language in {"ar","en","de"} else "ar";question=(question or "").strip()[:MAX_QUESTION_LENGTH]
 if not question:raise ValueError("question_required")
 ranked=sorted(((len(_tokens(question)&_tokens(a["keys"])),a) for a in ARTICLES),key=lambda x:x[0],reverse=True)
 selected=[a for score,a in ranked if score][:2] or [ARTICLES[0]]
 body="\n\n".join(a[language] for a in selected)
 if ACTION.search(question):
  refusal={"de":"Ich kann keine Daten ändern, freigeben, löschen, exportieren oder Aktionen im System ausführen. Ich kann nur den sicheren Ablauf erklären.","en":"I cannot change, approve, delete or export data, or perform system actions. I can only explain the safe procedure.","ar":"لا أستطيع تعديل البيانات أو اعتمادها أو حذفها أو تصديرها أو تنفيذ أي إجراء في النظام. يمكنني فقط شرح المسار الآمن."}[language]
  body=refusal+"\n\n"+body
 return {"answer":body,"topics":[a["id"] for a in selected],"sources":sorted({s for a in selected for s in a["sources"]}),"knowledge_version":VERSION,"isolation":{"read_only":True,"database_access":False,"network_access":False,"system_actions":False},"notice":{"de":"Beratungshilfe – keine amtliche Entscheidung.","en":"Guidance only – not an official decision.","ar":"مساعدة إرشادية وليست قراراً رسمياً."}[language]}
